services:

  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env.dev
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: .
    container_name: sora-api
    restart: always
    environment:
      DATABASE_URL:"mysql://dev:dev123@db:3306/sora_dev"
    depends_on:
      - db

volumes:
  mysql_data: 