services:
  db:
    image: mysql:8.0
    container_name: sora-mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_prod_data:/var/lib/mysql

  api:
    image: sora-api:latest
    container_name: sora-api
    restart: always
    env_file:
      - .env.prod
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: sora-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api

volumes:
  mysql_prod_data:
