FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma
COPY src ./src
COPY tsconfig.json ./

RUN npm install

RUN npx prisma generate

RUN npm run build

EXPOSE 3333

CMD ["node", "dist/server.js"]
